project/employee/forms.py
from flask_wtf import FlaskForm
from datetime import datetime,timedelta
from wtforms import StringField,BooleanField,PasswordField,SubmitField,DateField,FloatField,FileField,ValidationError
from wtforms.validators import DataRequired,Length,Email,EqualTo
from flask_wtf.file import FileRequired, FileAllowed
from project.models import Employee

class EmpLoginForm(FlaskForm):
    employeeid = StringField('Employee ID',validators=[DataRequired(),Length(2,20)])
    remember = BooleanField('Remember Me')
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Login')
    
class ExpenseForm(FlaskForm):
    date = DateField('Date', validators=[DataRequired()])
    amount = FloatField('Amount', validators=[DataRequired()])
    image_file = FileField('Picture', validators=[FileRequired(), FileAllowed(['jpg', 'jpeg', 'png', 'gif','pdf'], 'Images or pdfs only!')])
    submit = SubmitField('Submit')
    
    
    def validate_date(self, date):
        date_str = date.data.strftime('%Y-%m-%d')
        date = datetime.strptime(date_str, '%Y-%m-%d').date()
        today = datetime.now().date()
        if date < today - timedelta(days=30) or date > today:
            raise ValidationError('Date must be within the last 30 days')
    
class UpdateExpenseForm(FlaskForm):
    date = DateField('Date')
    amount = FloatField('Amount')
    image_file = FileField('Picture', validators=[ FileAllowed(['jpg', 'jpeg', 'png', 'gif','pdf'], 'Images or pdf only!')])
    submit = SubmitField('Submit')
    
    
    def validate_date(self, date):
        date_str = date.data.strftime('%Y-%m-%d')
        date = datetime.strptime(date_str, '%Y-%m-%d').date()
        today = datetime.now().date()
        if date < today - timedelta(days=30) or date > today:
            raise ValidationError('Date must be within the last 30 days')
    
class RequestRestForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    submit = SubmitField('Submit')
    
    def validate_email(self,email):
        emp = Employee.query.filter_by(email=email.data).first()
        if emp is None:
            raise ValidationError("Employee not exist. Please check your employee id")
        
class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password',validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField('Reset Password')

project/manager/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,BooleanField,PasswordField,SubmitField,SelectField,TextAreaField
from wtforms.validators import DataRequired,Length,Email,ValidationError
from wtforms import validators
class ManagerLoginForm(FlaskForm):
    managerid = StringField('Manager ID',validators=[DataRequired(),Length(2,20)])
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Login')
    


class StatusForm(FlaskForm):
    status_choices = [
        ("", ""),
        ("Issue with Picture/File", "Issue with Picture/File"),
        ("Expired Date/Issue with the Date", "Expired Date/Issue with the Date"),
        ("Invalid Amount", "Invalid Amount"),
        ("Non Acceptance", "Non Acceptance")
    ]
    
    def validate_reason_for_rejection(form, field):
        if form.rejected.data and not field.data:
            raise ValidationError("Reason for rejection is required.")
    
    reason_for_rejection = SelectField(
        'Reason for rejection', default="", choices=status_choices
    )
    
    rejected = SubmitField('Reject')
    accepted = SubmitField('Accept')
    # submit_rejection = SubmitField('Submit Rejection')

    # def validate(self):
    #     if self.rejected.data and not self.reason_for_rejection.data:
    #         self.reason_for_rejection.errors.append('Reason for rejection is required.')
    #         return False
    #     return True

    
class DeleteAdmin(FlaskForm):
    email = StringField("Admin's Email",validators=[DataRequired(),Email()])
    submit = SubmitField("Delete Admin")

project/employee/routes.py
from flask import Blueprint,redirect,render_template,url_for,flash,request,session
from project import db,bcrypt
from project.models import Employee
from project.employee.forms import EmpLoginForm,ExpenseForm,UpdateExpenseForm,RequestRestForm,ResetPasswordForm
from project.models import Expense
from project.employee.utils import save_picture,send_reset_email,send_claimid_mail_emp,send_claimid_mail_manager
import random
from datetime import datetime

employees = Blueprint('employees',__name__)


def generate_unique_claimid():
    """Generates a unique 7-digit number for the claimid attribute."""
    while True:
        claimid = random.randint(1000000, 9999999)
        if not Expense.query.filter_by(claimid=claimid).first():
            return claimid
        


@employees.route("/employee", methods=["GET", "POST"])
def employee():
    try:
        if 'employeeid' not in session:
            return redirect(url_for('employees.emp'))
        form = ExpenseForm()
        if form.validate_on_submit():
            # Process the form data
            claimid = generate_unique_claimid()
            expense = Expense(claimid=claimid,
                                empid=session['employeeid'],
                                date=form.date.data,
                                amount=form.amount.data,
                                image_file=save_picture(form.image_file.data),
                                managerid=session['managerid'],
                                manager_email = session['manager_email'],
                                reason_for_rejection = '-')
            time = datetime.now()
            print(f"Entering to the database {time}")
            db.session.add(expense)
            print(f"added to the database {datetime.now()-time}")
            db.session.commit()
            print(f"added to the database {datetime.now() - time}")
            flash('Expense has sent successfully!', 'success')
            employee = Employee.query.filter_by(employeeid=session['employeeid']).first()
            print(f"Preparing for sending a mail {datetime.now() - time}")
            send_claimid_mail_emp(employee, expense)
            print(f"Sent a mail to employee {datetime.now() - time}")
            send_claimid_mail_manager(employee, expense)
            print(f"sent a mail to manager {datetime.now() - time}")
            return redirect(url_for('employees.approve'))
        
        return render_template('employee.html', title = 'Expense Request',form=form)
    except Exception as e:
        # Log the error
        # Show a generic error message to the user
        flash(f'An error occurred while processing your request. Please try again later. {str(e)}', 'error')
        # Redirect the user to a safe page
        return redirect(url_for('employees.emp'))


@employees.route("/emp",methods=["GET","POST"])
def emp():
    form = EmpLoginForm()
    
    try:
        if form.validate_on_submit():
            employee = Employee.query.filter_by(employeeid=form.employeeid.data).first()
            if employee and bcrypt.check_password_hash(employee.password, form.password.data):
                session["employeeid"] = employee.employeeid
                session["managerid"] = employee.managerid
                session['name'] = employee.name
                session['manager_email'] = employee.manager_email
                
                return redirect(url_for('employees.employee'))
            else:
                flash('Login Unsuccessful. Please check Employee id and password', 'danger')
    except Exception as e:
        # Log the error
        print(f"An error occurred while logging in: {str(e)}")
        # Show a message to the user that the login was unsuccessful
        flash("An error occurred while logging in. Please try again later.", 'danger')
    return render_template('emp.html', title = 'Employee Login',form=form)


@employees.route('/approve')
def approve():  # replace with the actual employee ID
    try:
        if 'employeeid' not in session:
            return redirect(url_for('employees.emp'))
        page = request.args.get('page',1,type=int)
        expenses = Expense.query.filter_by(empid=session["employeeid"]).order_by(Expense.status.desc()).paginate(page=page, per_page=10)
        # print(expenses)
        if expenses:
            status_list = [[str(expense.date),expense.amount,expense.status,
                            str(expense.reason_for_rejection)] for expense in expenses]
            # print(f'the status list is {status_list}')
            if "rejected" in status_list:
                return redirect(url_for('employees.rejected'))
        else: 
            flash("Not yet sent any requests for expense claims")
            return redirect(url_for('employees.employee'))
        return render_template('approve.html',status_list=status_list,expenses=expenses)
    except Exception as e:
        # log the exception and display a user-friendly error message
        
        flash("An error occurred. Please try again later.")
        return redirect(url_for('employees.employee'))


@employees.route("/rejected",methods=["GET","POST"])
def rejected():
    time = datetime.now()
                
    try:
        if 'employeeid' not in session:
            return redirect(url_for('employees.emp'))
        form = UpdateExpenseForm()
        expense = Expense.query.filter_by(empid=session["employeeid"], status="rejected").first()
        if expense and form.validate_on_submit():
                if form.date.data:
                    expense.date = form.date.data
                if form.amount.data:
                    expense.amount = form.amount.data
                if form.image_file.data:
                    expense.image_file = save_picture(form.image_file.data, expense.image_file)
                expense.status = 'pending'
                expense.reason_for_rejection = '-'
                print(f"the time {time - datetime.now()}")
                db.session.commit()
                flash("Expense is updated successfully. Wait for the Manager Response")
                return redirect(url_for('employees.approve'))
            
        elif request.method == 'GET':
            form.date.data = expense.date
            form.amount.data = expense.amount
            # form.image_file.data = url_for('static', filename='bills/' + expense.image_file)
        return render_template('rejected.html', form=form, expense=expense)
    except Exception as e:
        # log the exception and display a user-friendly error message
        
        flash("An error occurred. Please try again later.")
        return redirect(url_for('employees.employee'))


# creating password reset form 
# requestform is use to send a request to the user for reset the email 
# resetpasswordform is used to reset the actual password 
    
@employees.route("/emp_reset_pass",methods=['GET','POST'])
def reset_request():
    try:
        if 'employeeid' in session:
            return redirect(url_for('employees.emp'))
        form = RequestRestForm()
        if form.validate_on_submit():
            emp = Employee.query.filter_by(email=form.email.data).first()
            send_reset_email(emp)
            flash('An email has been sent, for reset your password','info')
            return redirect(url_for('employees.emp'))
        return render_template('emp_request.html',title = 'Reset Password',form = form)
    except Exception as e:
        # log the exception and display a user-friendly error message
        
        flash("An error occurred. Please try again later.")
        return redirect(url_for('employees.emp'))




@employees.route("/emp_reset_pass/<token>",methods=['GET','POST'])
def reset_token(token):
    try:
        if 'employeeid' in session:
            return redirect(url_for('employees.emp'))
        emp = Employee.verify_reset_token_employee(token)
        if emp is None:
            flash('That is an invalid or expired token','warning')
            return redirect(url_for('employees.emp_request'))
        form = ResetPasswordForm()
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data)
            emp.password = hashed_password
            db.session.commit()
            flash('Your Password has been update! You are now able to log in')
            return redirect(url_for('employees.emp'))
        return render_template('emp_token.html',title='Reset Password',form = form)
    except Exception as e:
        # log the exception and display a user-friendly error message
        
        flash("An error occurred while resetting your password. Please try again later.")
        return redirect(url_for('employees.emp'))

            
        
@employees.route("/logout")
def logout():
    session.pop("employeeid", None)
    session.pop("managerid", None)
    session.pop("name",None)
    session.clear()
    return redirect(url_for("main.index"))

project/manager/routes.py
from flask import Blueprint,session,render_template,redirect,url_for,flash,request
from project import db,bcrypt
from project.manager.forms import ManagerLoginForm,StatusForm,DeleteAdmin
from project.models import Expense,Employee,User
from datetime import datetime
from project.manager.utlis import send_reject,send_accept,get_picture
managers = Blueprint('managers',__name__)


import base64

@managers.route("/manager_login", methods=["GET", "POST"])
def manager_login():
    form = ManagerLoginForm()
    try:
        if form.validate_on_submit():
            employee = Employee.query.filter_by(employeeid=form.managerid.data).first()
            if employee and employee.role == 'manager':
                if bcrypt.check_password_hash(employee.password, form.password.data):
                    session['managerid'] = employee.employeeid
                    session['name'] = employee.name
                    return redirect(url_for('managers.manager'))
                else:
                    flash("Please Check your Manager ID or Password",'danger')
            else:
                flash("Your are an employee only manager can access this page")
    except Exception as e:
        flash(f"An error occurred while logging in ", 'danger')
    return render_template('manager_login.html', form=form)



@managers.route("/manager", methods=['GET', 'POST'])
def manager():
    if 'managerid' not in session:
        return redirect(url_for('managers.manager_login'))

    try:
        page = request.args.get('page', 1, int)
        expenses = Expense.query.filter_by(managerid=session['managerid'], status='pending').paginate(page=page, per_page=5)
        time = datetime.now()
        print(f"the manager list {expenses}")
        print(f"starting timer {time}")
        manager_list = [[str(expense.date), expense.amount, expense.image_file, expense.claimid] for expense in expenses]
        print(f"the fetched time {datetime.now() - time}")
        form = StatusForm()

        if form.validate_on_submit():
            claimid = request.form.get("claimid")
            expense = Expense.query.filter_by(claimid=claimid, managerid=session['managerid'], status='pending').first()
            print(f"the fetched time 2 {datetime.now() - time}")
            if expense:
                employee = Employee.query.filter_by(employeeid=expense.empid).first()
                print(f"the fetched time 3 {datetime.now() - time}")
                if form.accepted.data == True:
                    expense.status = "accepted"
                    expense.reason_for_rejection = " "
                    send_accept(employee, expense=expense)
                elif form.rejected.data == True:
                    expense.status = "rejected"
                    expense.reason_for_rejection = form.reason_for_rejection.data
                    send_reject(employee, expense=expense)
                
                print(f"the end time {datetime.now() - time}")
                flash("Expense status updated successfully.")
                db.session.commit()
                return redirect(url_for("managers.manager"))
            else:
                flash("No response yet.")
                return redirect(url_for("managers.manager"))

        return render_template('manager.html',title = 'Expense Request', manager_list=manager_list, expenses=expenses,get_picture=get_picture, form=form)
        
    except Exception as e:
        flash("An error occurred. Please try again later str{e}.")
        print(str(e))
        return redirect(url_for("managers.manager"))



@managers.route("/delete_admin",methods = ["POST","GET"])
def delete_admin():
    if 'managerid' not in session:
        return redirect(url_for('managers.manager_login'))
    form = DeleteAdmin()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email = form.email.data).first()
            if user:
                db.session.delete(user)
                db.session.commit()
                flash("An Admin deleted successfully",'success')
            else:
                flash("Admin not found, please check admin's email",'warning')
                return redirect(url_for('managers.delete_admin'))
        except Exception as e:
            flash("An error occurred while deleting the admin.", 'danger')
            return redirect(url_for('managers.delete_admin'))
    return render_template("delete_admin.html",form = form)


@managers.route("/logout")
def logout():
    session.pop("managerid", None)
    session.pop("name", None)
    session.clear()
    return redirect(url_for("managers.manager_login"))

project/templates/approve.html
<title>Employee Page</title>
{% extends "index.html" %}
{% block content%}

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hello {{session['name']}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="{{url_for('employees.employee')}}" class="nav-link" style="color: black;">Home</a>
        </li>
        <li class="nav-item">
          <a href="{{url_for('employees.logout')}}" class="nav-link" style="color: black;">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>



 
    <div class="col-md-8 mx-auto text-center">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }} text-danger" id="alert-success">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>


<div class="container-fluid mx-auto" style="position: relative;">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 text-center" style="background-color: #ECF2FF; padding: 10px;">
      <table>
        <thead>
          <tr>
            <th>Date of the bill</th>
            <th>Amount to be claimed</th>
            <th>Status</th>
            <th>Reason</th>
          </tr>
        </thead>
        <tbody>
          {% for status in status_list %}
              <tr>
                <td data-label="Date of the bill">{{ status[0] }}</td>
                <td data-label="Amount to be claimed">{{ status[1] }}</td>
                <td data-label="Status">
                  {% if status[2] == 'pending' %}
                    <p class="text-center" style="color: blue;">Pending</p>
                  {% elif status[2] == 'rejected' %}
                  <p class="text-center" style="color: red;">Rejected</p>
                    {% if status[3] != 'Non Acceptance'  %}
                      <a href="{{ url_for('employees.rejected') }}" class="btn btn-outline-info">Update</a>
                    
                      
                    {% endif %}
                  {% elif status[2] == 'accepted' %}
                    <p class="text-center" style="color: green;">Approved</p>
                  {% endif %}
                </td>
                <td data-label="Reason">{{status[3]}}</td>

              </tr >

          {% endfor %}
        </tbody>
      </table>
    
    </div>
    <br>
  </div>
</div>
<br>
<div class="pagination justify-content-center">
  {% if expenses.has_prev %}
    <a class="btn btn-outline-info mb-4  mx-1" href="{{ url_for('employees.approve', page=expenses.prev_num) }}" >&laquo;</a>
  {% else %}
    <a class="btn btn-outline-info mb-4 disabled  mx-1">&laquo;</a>
  {% endif %}
  {% for page in expenses.iter_pages() %}
    {% if page %}
      {% if page == expenses.page %}
        <a class="btn btn-outline-info mb-4 active mx-1">{{ page }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4  mx-1" href="{{ url_for('employees.approve', page=page) }}">{{ page }}</a>
      {% endif %}
    {% else %}
      <span class="btn btn-outline-info mb-4 disabled mx-1">...</span>
    {% endif %}
  {% endfor %}
  {% if expenses.has_next %}
    <a class="btn btn-outline-info mb-4 mx-1" href="{{ url_for('employees.approve', page=expenses.next_num) }}">&raquo;</a>
  {% else %}
    <a class="btn btn-outline-info mb-4 disabled mx-1">&raquo;</a>
  {% endif %}
</div>



{% endblock %}

project/templates/delete_admin.html
{% extends "index.html" %}
{% block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light blue">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hello {{session['name']}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{{url_for('managers.manager')}}" class="nav-link a1" style="color: black;">Home</a>
        </li>
        <li class="nav-item">
          <a href="{{url_for('managers.logout')}}" class="nav-link a1" style="color: black;">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <div class="col-md-8 mx-auto text-center">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }} text-info" id="alert-success">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>


    <br>
    <div class="container" id="register">
      <form method="POST" action="" id="form">
        {{form.hidden_tag()}}
        <legend class="text-center mb-4">Delete Employee</legend>
        <div class="form-group mb-2">
            {{ form.email.label(class="form-control-label") }}
    
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
    
        <div class = "form-group text-center">
        <button type="button" class="btn btn-outline-info" onclick="confirmDelete()">Delete</button>
        </div>
    
    </form>
    </div>
    
    <script>
    function confirmDelete() {
        if (confirm("Are you sure you want to delete this Admin?")) {
            document.getElementById("form").submit();
        }
    }
    </script>

{% endblock %}
        

project/templates/emp.html
<title>Employee Page</title>
{% extends "index.html" %}
{% block content %}
    <div class="col-md-8 mx-auto text-center">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} text-danger" id="alert-success">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    <div class="container d-flex justify-content-center align-items-center mt-4" style="min-height: 100%;">
        <div class="card text-dark bg-light p-4 col-md-6" style="max-width: 30rem;">
          <div class="card-body">
            <form method="POST" action="" class="form">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                <legend class="border-bottom mb-4">Employee Login</legend>
                <div class="form-group mb-3">
                  {{ form.employeeid.label(class="form-control-label") }}
                  {% if form.employeeid.errors %}
                  {{ form.employeeid(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.employeeid.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %}
                  {{ form.employeeid(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
                <div class="form-group mb-3">
                  {{ form.password.label(class="form-control-label") }}
                  {% if form.password.errors %}
                  {{ form.password(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %}
                  {{ form.password(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
              </fieldset>
              <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
              </div>
            </form>
            <small class="text-muted ml-2">
              <a href="{{ url_for('employees.reset_request') }}" style="text-decoration:None;">Forgot Password?</a>
            </small>
          </div>
        </div>
      </div>
      

{% endblock content %}

project/templates/manager.html
<title>Manager Page</title>
{% extends "index.html" %}
{% block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light blue">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hello {{session['name']}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{{url_for('managers.delete_admin')}}" class="nav-link a1" style="color: black;">Delete Admin</a>
        </li>
        <li class="nav-item">
          <a href="{{url_for('managers.logout')}}" class="nav-link a1" style="color: black;">Log out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="col-md-8 mx-auto text-center">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }} text-danger" id="alert-success">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
  <div class="container-fluid mt-5 mx-auto">
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-12 text-center" style="background-color: #ECF2FF; padding: 10px;">
        <table>
          <thead>
            <tr>
              <th>Date of the bill</th>
              <th>Amount to be claimed</th>
              <th>Picture</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for expense in manager_list %}
            <tr>
              <td data-label="Date of the bill">{{ expense[0] }}</td>
              <td data-label="Amount to be claimed">{{ expense[1] }}</td>
              <td data-label="Picture/Files">
                {% if expense[2].endswith('.pdf') %}
                    <a href="{{ get_picture(expense[2]) }}" target="_blank" style="text-decoration:none;">PDF file</a>
                {% else %}
                    <a href="{{ get_picture(expense[2]) }}" target="_blank">
                        <img src="{{ get_picture(expense[2]) }}" width="100" height="100">
                    </a>
                {% endif %}
            </td>

              <td data-label="Status">
                <div class="container text-center">
                  <form method="POST">
                    {{ form.hidden_tag() }}
                    <input type="hidden" name="claimid" value="{{ expense[3] }}">
                    <div class='mb-3'>
                      {{ form.rejected(class="btn btn-outline-info btn-block mb-2 font-weight-bold") }}
                    </div>
                    <div class='mb-3'>
                      {{ form.accepted(class="btn btn-outline-info btn-block font-weight-bold") }}
                    </div>
                    <div class="mb-3">
                      {{ form.reason_for_rejection.label(class="form-control-label") }}
                      {{ form.reason_for_rejection(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.reason_for_rejection.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    </div>
                    
                  </form>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

 

<br>
  <div class="pagination justify-content-center" >
    {% if expenses.has_prev %}
      <a class="btn btn-outline-info mb-4  mx-1" href="{{ url_for('employees.approve', page=expenses.prev_num) }}" >&laquo;</a>
    {% else %}
      <a class="btn btn-outline-info mb-4 disabled  mx-1">&laquo;</a>
    {% endif %}
    {% for page in expenses.iter_pages() %}
      {% if page %}
        {% if page == expenses.page %}
          <a class="btn btn-outline-info mb-4 active mx-1">{{ page }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4  mx-1" href="{{ url_for('employees.approve', page=page) }}">{{ page }}</a>
        {% endif %}
      {% else %}
        <span class="btn btn-outline-info mb-4 disabled mx-1">...</span>
      {% endif %}
    {% endfor %}
    {% if expenses.has_next %}
      <a class="btn btn-outline-info mb-4 mx-1" href="{{ url_for('employees.approve', page=expenses.next_num) }}">&raquo;</a>
    {% else %}
      <a class="btn btn-outline-info mb-4 disabled mx-1">&raquo;</a>
    {% endif %}
  </div>
{% endblock %}